version: '3.8'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/cinema_project
    command:
      sh -c 'python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata films.json &&
             python manage.py loaddata rooms.json &&
             python manage.py loaddata cast.json &&
             python manage.py loaddata dates.json &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000'
    env_file:
      - ./cinema_project/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379"

  celery:
    restart: always
    build: .
    command: celery -A cinema_project worker -l info
    volumes:
      - .:/cinema_project
    env_file:
      - ./cinema_project/.env
    depends_on:
      - redis
      - app

  celery_beat:
    restart: always
    build: .
    command: celery -A cinema_project beat -l info
    volumes:
      - .:/cinema_project
    env_file:
      - ./cinema_project/.env
    depends_on:
      - redis
      - app

  flower:
    build: .
    command: celery -A cinema_project flower --port=3535
    volumes:
      - .:/cinema_project
    env_file:
      - ./cinema_project/.env
    ports:
      - '3535:3535'
    depends_on:
      - redis
      - app
      - celery

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: