# Generated by Django 4.2 on 2023-04-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaPremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=250, verbose_name='Film')),
                ('description', models.TextField(verbose_name='Description')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('trailer', models.URLField(verbose_name='Trailer')),
                ('image', models.ImageField(upload_to='uploads/film_posters/', verbose_name='Film Poster')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='CinemaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(verbose_name='Cinema Room')),
                ('number_of_tickets', models.IntegerField(verbose_name='Number of Available tickets')),
            ],
            options={
                'verbose_name': 'Cinema Room',
                'verbose_name_plural': 'Cinema Rooms',
            },
        ),
        migrations.CreateModel(
            name='ShowDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Show Date')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdate', to='cinema_app.cinemapremiere', verbose_name='Film')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdate', to='cinema_app.cinemaroom', verbose_name='Cinema Room')),
            ],
            options={
                'verbose_name': 'Show Date',
                'verbose_name_plural': 'Show Dates',
                'unique_together': {('date', 'room')},
            },
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=128, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cinema_app.showdate', verbose_name='Show Date')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cinema_app.cinemapremiere', verbose_name='Film')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cinema_app.cinemaroom', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Pre-Order',
                'verbose_name_plural': 'Pre-Orders',
            },
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=250, verbose_name='Actor Name')),
                ('role', models.CharField(max_length=250, verbose_name='Role')),
                ('image', models.ImageField(upload_to='uploads/actors/', verbose_name='Actor image')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='cinema_app.cinemapremiere', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Cast',
                'verbose_name_plural': 'Cast',
            },
        ),
    ]
