# Generated by Django 4.2 on 2023-04-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_cinemapremiere_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='room',
        ),
    ]
