# Generated by Django 4.2 on 2023-04-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_remove_preorder_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemapremiere',
            name='trailer',
            field=models.FileField(upload_to='uploads/film_trailers/', verbose_name='Trailer'),
        ),
    ]
