# Generated by Django 4.2 on 2023-04-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_alter_cinemapremiere_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='phone_number',
            field=models.CharField(verbose_name='Phone Number'),
        ),
    ]
