# Generated by Django 4.2 on 2023-04-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0005_alter_preorder_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('phone_number', models.CharField(verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cinema_app.showdate', verbose_name='Show Date')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cinema_app.cinemapremiere', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Pre-Order',
                'verbose_name_plural': 'Pre-Orders',
            },
        ),
        migrations.DeleteModel(
            name='PreOrder',
        ),
    ]
