# Generated by Django 4.2 on 2023-04-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_order_delete_preorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
