# Generated by Django 4.2 on 2023-04-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0010_remove_order_email_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_ticket',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/qr_tickets', verbose_name='QR ticket'),
        ),
    ]
